### ISSUE TITLE
HA Statistics

### ISSUE THREAD

**Issue by lalarsson87** [CiscoCloud/haproxy-consul#34]
Hi,

I love this project - it works perfectly together with my Consul environment! Thank you so much for your work!

One thing I'd like in this project is the ability to enable/disable HA statistics. I can add it myself in a PR but I'd like to know if there is any reason for it not already being implemented?

**Comment by stevendborrelli** [comment]
No, please open an PR.

**Comment by lalarsson87** [comment]
I've opened a PR #35 for it.

**Comment by lalarsson87** [comment]
PR #35 merged!
