### ISSUE TITLE
Some old PRs?

### ISSUE THREAD

**Issue by lalarsson87** [CiscoCloud/haproxy-consul#36]
Hi again! :)

I was reading up on existing PRs after creating my own and saw some issues being fixed that I'd very much like to use in my environment.

I could help out with reviewing these changes if that could speed up merges?

Cheers!

**Comment by stevendborrelli** [comment]
That would be awesome. I'll merge them quickly. Just make sure to @ me.

**Comment by lalarsson87** [comment]
Alright! :)

**Comment by auguster** [comment]
Can you close the outdated PR please. I don't see the point in leaving them open.
In case you don't know, here is how: https://help.github.com/articles/closing-a-pull-request/ ;-)
